import React from 'react';
import { Link } from 'react-router-dom';
import { Home, TrendingUp, BarChart3, Users, Clock, DollarSign, AlertTriangle } from 'lucide-react';

export default function AdvancedAnalytics() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900"><div className="bg-white/10 backdrop-blur-xl border-b border-white/20"><div className="max-w-7xl mx-auto px-6 py-4"><div className="flex items-center gap-4"><Link to="/command-center"><Home className="w-5 h-5 text-purple-400" /></Link><div className="h-6 w-px bg-white/20" /><h1 className="text-2xl font-black text-white flex items-center gap-2"><BarChart3 className="w-7 h-7 text-purple-400" />Advanced Analytics 📊</h1></div></div></div><div className="max-w-7xl mx-auto p-6 space-y-6"><div className="grid grid-cols-4 gap-6">{[{icon:Users,label:'Total Employees',value:'45',change:'+3%',color:'blue'},{icon:Clock,label:'Avg Hours/Week',value:'38.5',change:'-2%',color:'purple'},{icon:DollarSign,label:'Labor Cost',value:'$125K',change:'+5%',color:'green'},{icon:AlertTriangle,label:'Open Shifts',value:'12',change:'-15%',color:'yellow'}].map((stat,i)=>{const Icon=stat.icon;return(<div key={i} className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6"><Icon className={`w-10 h-10 text-${stat.color}-400 mb-3`}/><div className="text-3xl font-bold text-white mb-1">{stat.value}</div><div className="text-purple-200 text-sm mb-2">{stat.label}</div><div className={`text-sm ${stat.change.startsWith('+')?'text-green-400':'text-red-400'}`}>{stat.change} vs last month</div></div>);})}</div><div className="grid grid-cols-2 gap-6"><div className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6"><h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2"><TrendingUp className="w-6 h-6 text-purple-400"/>Scheduling Efficiency</h2><div className="space-y-4">{['Peak Hours Coverage: 98%','Overtime Reduction: 22%','Shift Fill Rate: 94%','Employee Satisfaction: 4.7/5'].map((metric,i)=>(<div key={i} className="flex justify-between items-center p-3 bg-white/5 rounded-lg"><span className="text-white">{metric.split(':')[0]}</span><span className="text-purple-400 font-bold">{metric.split(':')[1]}</span></div>))}</div></div><div className="bg-white/10 backdrop-blur-xl border border-white/20 rounded-2xl p-6"><h2 className="text-xl font-bold text-white mb-4">AI Insights & Predictions</h2><div className="space-y-3">{['Predicted staffing shortage next Tuesday PM shift','Overtime likely to exceed budget by 8% this month','Employee turnover risk identified for 2 team members','Recommend hiring 3 additional part-time staff'].map((insight,i)=>(<div key={i} className="p-3 bg-purple-600/30 border-l-4 border-purple-400 rounded text-white text-sm">{insight}</div>))}</div></div></div></div></div>
  );
}
